version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: lakehouse_postgres
    environment:
      POSTGRES_USER: lakehouse
      POSTGRES_PASSWORD: lakehouse
      POSTGRES_DB: lakehouse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: